image: docker:stable

services:
- docker:dind
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 

before_script:
- docker info

build-docker:
  stage: build
  script:
  - docker build -t my-image .